version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = ["nodejs", "bun"]
  module_system = "es-modules"
  dialect = "typescript"

[[analyzers]]
name = "secrets"
enabled = true

test_patterns = []

exclude_patterns = [
  "examples/**",
  "dist/**",
  "node_modules/**",
  "scripts/**",
  "**/*.config.ts",
  "**/*.config.js",
  "**/*.test.ts",
  "tests/**"
]
